### ISSUE TITLE
Typo in Chapter 4

### ISSUE THREAD

**Issue by prebleka** [PsyTeachR/stat-models-v1#14]
In chapter 4 at the bottom of the page, it says:

![Screenshot 2024-05-25 at 2 16 28 PM](https://github.com/PsyTeachR/stat-models-v1/assets/170825363/1a1c6691-fa27-4391-b5a8-d8c469f450ab)

I think the "is" should be an "in"?

Great resource -- thanks for sharing!

**Comment by dalejbarr** [comment]
Thanks for spotting this. Fixed in 715cfaaed420df04791b0a8ab526ef998d76b644
