### ISSUE TITLE
'Figure 8.2: Logistic regression web app' does not load (Posit license has expired)

### ISSUE THREAD

**Issue by hanneoberman** [PsyTeachR/stat-models-v1#16]
Hi, love your books! But there's an image not loading on https://psyteachr.github.io/stat-models-v1/generalized-linear-mixed-effects-models.html

![image](https://github.com/user-attachments/assets/d1adeb4d-b882-4a6e-aee2-298c77a9cbe3)

**Comment by dalejbarr** [comment]
Thanks for letting us know. Our shiny server was discontinued, and so all apps needed to be converted into standalone apps using the 'shinylive' package. The broken links should work again.

Fixed in commit 2ae1980a3d51eb54cb8ab35767eb915c6e62aca3
